version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      BUILD_DIR: dist
      
      PORT: 5173
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5173 >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 20s
    restart: unless-stopped
